apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: my-container
        image: <YOUR_IMAGE_URI> # e.g., your-account-id.dkr.ecr.us-east-1.amazonaws.com/repo:tag
        ports:
        - containerPort: 8080
        command: ["/bin/bash", "-c"]
        args: ["/update.sh && catalina.sh run"]
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the Load Balancer
      targetPort: 8080 # Port your application is listening on
