apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  # The selector must match the labels defined in your Deployment's pod template
  selector:
    app: springapp
  type: NodePort # This type exposes the service on each node's IP at a static port
  ports:
    - protocol: TCP
      port: 8080 # The port the service will listen on inside the cluster
      targetPort: 80
